
// ELEMENT_ID用于自动化id

// 视图选择
export const VIEW_SELECT = 'VIEW_SELECT'
export const FILTERBAR = {
  FILTERFIELD: 'FILTERFIELD',
  FUZZY_SCREEN: 'FUZZY_SCREEN',
  SENIOR_FILTER: 'SENIOR_FILTER',
  REFRESH: 'REFRESH',
  RESET: 'RESET'
}
export const SELECTALL = 'SELECTALL'
export const ACTIONBAR = {
  ACTIONBAR: 'ACTIONBAR'
}
// export const FILTERFIELD = 'FILTERFIELD'
// export const FUZZY_SCREEN = 'FUZZY_SCREEN'

export default VIEW_SELECT
