// eslint-disable-next-line @typescript-eslint/restrict-template-expressions
export const getIconSrc = (iconName?: string): string => `/assets/icons/${iconName}.svg`;
export const getIconRelativePath = (iconName?: string): string => `@/../public/assets/icons/${iconName}.svg`;

export const iconNames = {
  children: 'numberOfChildren',
  rowCount: 'numberOfRows',
  columnCount: 'numberOfColumns',
  rowHeight: 'rowHeight',
  columnWidth: 'columnWidth',
  rowGap: 'rowGap',
  columnGap: 'columnGap',
  direction: { // grid-auto-flow: row dense;中的row/column属性
    row: 'IconFlowRow',
    column: 'IconFlowCol',
  },
  emptySpace: {
    fill: 'IconFlowDense', // grid-auto-flow: row dense;中的dense属性
    dontFill: '',
  },
  align: {
    justifyContent: { // justify-content
      center: 'IconJustifyCenter',
      // end: 'IconJustifyEnd',
      // start: 'IconJustifyStart',
      stretch: 'IconJustifyStretch',
      'space-around': 'IconJustifySpaceAround',
      'space-between': 'IconJustifySpaceBetween',
      'space-evenly': 'IconJustifySpaceEvenly',
      // left: '',
      // right: '',
      'flex-start': 'IconJustifyEnd',
      'flex-end': 'IconJustifyStart',
    },
    alignContent: { // align-content
      center: 'IconAlignCenter',
      end: 'IconAlignEnd',
      start: 'IconAlignStart',
      stretch: 'IconAlignStretch',
      'space-around': 'IconAlignSpaceAround',
      'space-between': 'IconAlignSpaceBetween',
      'space-evenly': 'IconAlignSpaceEvenly',
      baseline: '',
      'flex-start': '',
      'flex-end': '',
    },
  },
  items: {
    justifyItems: { // justify-items
      center: 'IconJustifyCenter',
      end: 'IconJustifyEnd',
      start: 'IconJustifyStart',
      stretch: 'IconJustifyStretch',
      left: '',
      right: '',
      legacy: '',
      'flex-start': '',
      'flex-end': '',
      baseline: '',
      selfStart: '',
      selfEnd: '',
    },
    alignItems: { // align-items
      center: 'IconAlignCenter',
      end: 'IconAlignEnd',
      start: 'IconAlignStart',
      stretch: 'IconAlignStretch',
      'flex-start': '',
      'flex-end': '',
      baseline: '',
      selfStart: '',
      selfEnd: '',
    },
  },
  self: {
    justifySelf: { // justify-self
      center: 'IconJustifyCenter',
      end: 'IconJustifyEnd',
      start: 'IconJustifyStart',
      stretch: 'IconJustifyStretch',
      left: '',
      right: '',
      legacy: '',
      'flex-start': '',
      'flex-end': '',
      baseline: '',
      selfStart: '',
      selfEnd: '',
    },
    alignSelf: { // align-self
      center: 'IconAlignCenter',
      end: 'IconAlignEnd',
      start: 'IconAlignStart',
      stretch: 'IconAlignStretch',
      'flex-start': '',
      'flex-end': '',
      baseline: '',
      selfStart: '',
      selfEnd: '',
    },
  },
};
